let questions_data = [
  {
    category: 'animals',
    name: 'Tiere',
    img: './img/animals.jpg',
    questions: [
      {
        question: 'Wie viele Zehen haben die meisten Vögel?',
        answer_1: 'zwei',
        answer_2: 'drei',
        answer_3: 'vier',
        answer_4: 'fünf',
        right_answer: 3,
      },
      {
        question: 'Wie heißt die größte Hirschart?',
        answer_1: 'Elch',
        answer_2: 'Karibu',
        answer_3: 'Riesenhirsch',
        answer_4: 'Wapiti',
        right_answer: 1,
      },
      {
        question: 'Wie nennt man schwarze Pferde?',
        answer_1: 'Schimmel',
        answer_2: 'Rappen',
        answer_3: 'Blacky',
        answer_4: 'Erzen',
        right_answer: 2,
      },
      {
        question: 'Wie viele Eier legt ein Haushuhn im Jahr?',
        answer_1: 'ca. 50',
        answer_2: 'ca. 100',
        answer_3: 'ca. 150',
        answer_4: 'ca. 200',
        right_answer: 4,
      },
      {
        question:
          'Werden Wale und Delphine mit dem Kopf oder mit dem Schwanz voraus geboren?',
        answer_1: 'Mit dem Schwanz',
        answer_2: 'Mit dem Kopf',
        answer_3: '',
        answer_4: '',
        right_answer: 1,
      },
      {
        question: 'Wie schwer kann ein Blauwal werden?',
        answer_1: 'Bis zu 10 Tonnen',
        answer_2: 'Bis zu 50 Tonnen',
        answer_3: 'Bis zu 100 Tonnen',
        answer_4: 'Bis zu 200 Tonnen',
        right_answer: 4,
      },
      {
        question: 'Wieso heißt der Waschbär eigentlich Waschbär?',
        answer_1: 'Er wurde das erste Mal in Washington entdeckt.',
        answer_2: 'Er schwimmt leidenschaftlich gerne',
        answer_3: 'Er treibt sich hauptsächlich in Waschküchen rum.',
        answer_4: 'Er ist besonders reinlich.',
        right_answer: 4,
      },
      {
        question: 'Was stimmt?',
        answer_1: 'Zebras haben ein schwarzes Fell mit weißen Streifen.',
        answer_2: 'Zebras haben ein weißes Fell mit schwarzen Streifen.',
        answer_3: '',
        answer_4: '',
        right_answer: 1,
      },
    ],
  },
  {
    category: 'computer',
    name: 'Computer',
    img: './img/computer.jpg',
    questions: [
      {
        question: 'Wie nennt man den Text einer Programmierung?',
        answer_1: 'Zielcode',
        answer_2: 'Apokryphen',
        answer_3: 'Hieroglyphen',
        answer_4: 'Quellcode',
        right_answer: 4,
      },
      {
        question:
          'Was verstärkt ankommende Signale und leitet sie im Netzwerk weiter?',
        answer_1: 'Schub',
        answer_2: 'Sub',
        answer_3: 'Dub',
        answer_4: 'Switch',
        right_answer: 4,
      },
      {
        question: 'In welche Firmen war Elon Musk im April 2023 im Vorstand?',
        answer_1: 'Tesla und Twitter',
        answer_2: 'Uber und Snapchat',
        answer_3: 'Twitter und Uber',
        answer_4: 'Snapchat und Tesla',
        right_answer: 1,
      },
      {
        question: 'In 2021 hat Facebook seinen Firmannamen wie folgt geändert:',
        answer_1: 'Alphabet',
        answer_2: 'Cisco',
        answer_3: 'Horizon',
        answer_4: 'Meta',
        right_answer: 4,
      },
      {
        question:
          'Wie viele Nachrichten werden pro Stunde über WhatsApp verschickt?',
        answer_1: 'ca. 6.000.000',
        answer_2: 'ca. 14.000.000',
        answer_3: 'ca. 22.000.000',
        answer_4: 'ca. 42.000.000',
        right_answer: 4,
      },
      {
        question:
          "Manchmal fängt eine URL mit 'https:' und manchmal mit 'http:' an. Was verspricht das 's'?",
        answer_1: 'einen altersgerechten Zugang für Kinder',
        answer_2: 'eine vor Viren geschützte Website',
        answer_3: 'Verschlüsselung und somit Sicherheit',
        answer_4: 'Nichts, es ist nur ein Fehler.',
        right_answer: 3,
      },
      {
        question: 'In welchem Jahr wurde das erste YouTube-Video hochgeladen?',
        answer_1: '2009',
        answer_2: '2005',
        answer_3: '1999',
        answer_4: '2007',
        right_answer: 2,
      },
      {
        question: "Wofür steht das 'I' in der Abkürzung 'MINT'?",
        answer_1: 'Institution',
        answer_2: 'Interdisziplinär',
        answer_3: 'Informatik',
        answer_4: 'Info',
        right_answer: 3,
      },
    ],
  },
  {
    category: 'coding',
    name: 'Programmieren',
    img: './img/coding.png',
    questions: [
      {
        question: 'Was bedeutet HTML ausgeschrieben?',
        answer_1: 'Hypertext Markup Language',
        answer_2: 'Hypertext Main Logic',
        answer_3: 'Highend Text Manager Languane',
        answer_4: 'Hausgemachte Tanzende Mäuse Lampe',
        right_answer: 1,
      },
      {
        question: 'Wie wird eine Webseite designed?',
        answer_1: 'Mit PHP',
        answer_2: 'Mit CSS',
        answer_3: 'Mit Java',
        answer_4: 'Mit Python',
        right_answer: 2,
      },
      {
        question: 'Wofür steht CSS?',
        answer_1: 'Controled Server System',
        answer_2: 'Circle Custom Server',
        answer_3: 'Calculated Control Server',
        answer_4: 'Cascading Style Sheets',
        right_answer: 4,
      },
      {
        question: 'Was ist WannaCry?',
        answer_1:
          'Ein Spiel, in dem es darum geht, ein Mädchen sehr gut zu pflegen, damit es nicht weint.',
        answer_2: 'Ein Liebestester',
        answer_3: 'Ein Programm zum simulieren eines weinendes Aliens',
        answer_4:
          'Ein Programm, dass sehr viele Computer auf der ganzen Welt gehackt hat',
        right_answer: 4,
      },
      {
        question: 'Wie werden z.B. Anmeldedaten in einer Tabelle gespeichert?',
        answer_1: 'Über Javascript',
        answer_2: 'Über Python',
        answer_3: 'Über SQL',
        answer_4: 'Über HTML',
        right_answer: 3,
      },
      {
        question: 'Wann wurde die Programmiersprache Javascript eingeführt?',
        answer_1: '1987',
        answer_2: '1995',
        answer_3: '1998',
        answer_4: '2002',
        right_answer: 2,
      },
    ],
  },
  {
    category: 'cars',
    name: 'Autos',
    img: './img/car.jpg',
    questions: [
      {
        question:
          'Dieses Auto motorisierte die Massen. Es war erschwinglich, technisch anspruchslos und wurde einige Jahrzehnte gebaut.',
        answer_1: 'Fiat 600',
        answer_2: 'VW Käfer',
        answer_3: 'Citroën 2CV',
        answer_4: 'Audi A4',
        right_answer: 2,
      },
      {
        question:
          'Dieses Auto wurde in den 1970er Jahren in Deutschland gebaut und sprach vor allem Familienväter an.',
        answer_1: 'BMW 3er',
        answer_2: 'Ford Escort',
        answer_3: 'Audi 80',
        answer_4: 'VW Golf',
        right_answer: 3,
      },
      {
        question: 'Die Handbremse...',
        answer_1: 'Bremst nur die Hinterräder',
        answer_2: 'Drückt die Fußbremse und hält sie gedrückt',
        answer_3: 'Bremst Vorder- und Hinterräder',
        answer_4: 'Bremst nur die Vorderräder',
        right_answer: 1,
      },
      {
        question: 'Was ist ein Otto-Motor?',
        answer_1: 'Ein Elektro-Motor',
        answer_2: 'Jede Art von Verbrennungsmotor',
        answer_3: 'Ein Dieselmotor',
        answer_4: 'Ein Benzinmotor',
        right_answer: 4,
      },
      {
        question:
          'Wo liegt, technisch betrachtet, der Hauptunterschied zwischen einem Benzin- und einem Dieselmotor?',
        answer_1:
          'Beim Dieselmotor wird das Gemisch durch Druck statt durch Zündkerzen gezündet',
        answer_2:
          'Ein Dieselmotor kann über einen Turbo verfügen, der Benzinmotor nicht',
        answer_3:
          'Der Dieselmotor könnte auch mit Benzin betrieben werden, der Benzinmotor aber nicht mit Diesel',
        answer_4:
          'Die Zahl der Zylinder kann bei Benzinmotoren frei gewählt werden, bei einem Dieselmotor müssen es immer 4 sein',
        right_answer: 1,
      },
      {
        question: 'Was macht das ABS?',
        answer_1: 'Es verhindert das Untersteuern des Fahrzeugs',
        answer_2: 'Es verhindert das Ausbrechen (Übersteuern) des Fahrzeugs',
        answer_3:
          'Es verhindert das Blockieren der Räder bei einer Vollbremsung',
        answer_4: 'Es verhindert das Durchdrehen der Räder beim Anfahren',
        right_answer: 3,
      },
    ],
  },
];

// let animals = [
//   {
//     question: "Wie viele Zehen haben die meisten Vögel?",
//     answer_1: "zwei",
//     answer_2: "drei",
//     answer_3: "vier",
//     answer_4: "fünf",
//     right_answer: 3,
//   },
//   {
//     question: "Wie heißt die größte Hirschart?",
//     answer_1: "Elch",
//     answer_2: "Karibu",
//     answer_3: "Riesenhirsch",
//     answer_4: "Wapiti",
//     right_answer: 1,
//   },
//   {
//     question: "Wie nennt man schwarze Pferde?",
//     answer_1: "Schimmel",
//     answer_2: "Rappen",
//     answer_3: "Blacky",
//     answer_4: "Erzen",
//     right_answer: 3,
//   },
//   {
//     question: "Wie viele Eier legt ein Haushuhn im Jahr?",
//     answer_1: "ca. 50",
//     answer_2: "ca. 100",
//     answer_3: "ca. 150",
//     answer_4: "ca. 200",
//     right_answer: 4,
//   },
//   {
//     question:
//       "Werden Wale und Delphine mit dem Kopf oder mit dem Schwanz voraus geboren?",
//     answer_1: "Mit dem Schwanz",
//     answer_2: "Mit dem Kopf",
//     answer_3: "",
//     answer_4: "",
//     right_answer: 1,
//   },
//   {
//     question: "Wie schwer kann ein Blauwal werden?",
//     answer_1: "Bis zu 10.000 Kilogramm",
//     answer_2: "Bis zu 50.000 Kilogramm",
//     answer_3: "Bis zu 100.000 Kilogramm",
//     answer_4: "Bis zu 200.000 Kilogramm",
//     right_answer: 4,
//   },
//   {
//     question: "Wieso heißt der Waschbär eigentlich Waschbär?",
//     answer_1: "Er wurde das erste Mal in Washington entdeckt.",
//     answer_2: "Er schwimmt leidenschaftlich gerne",
//     answer_3: "Er treibt sich hauptsächlich in Waschküchen rum.",
//     answer_4: "Er ist besonders reinlich.",
//     right_answer: 4,
//   },
//   {
//     question: "Was stimmt?",
//     answer_1: "Zebras haben ein schwarzes Fell mit weißen Streifen.",
//     answer_2: "Zebras haben ein weißes Fell mit schwarzen Streifen.",
//     answer_3: "",
//     answer_4: "",
//     right_answer: 1,
//   },
// ];
